on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish site
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 11ty
        id: 11ty
        uses: burgess01/11ty-action@v0.1.3-alpha
        with:
          directory: src
