on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish site
    steps:
      - name: 11ty
        id: eleventy
        uses: burgess01/11ty-action@v0.1.3-alpha
        with:
          directory: src
